// Code generated by Kitex v0.2.1. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"userser/kitex_gen/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserSignUp(ctx context.Context, Req *user.UserSignUpRequest, callOptions ...callopt.Option) (r *user.UserSignUpResponse, err error)
	UserLogIn(ctx context.Context, Req *user.UserLogInRequest, callOptions ...callopt.Option) (r *user.UserLogInResponse, err error)
	UserLogOut(ctx context.Context, Req *user.UserLogOutRequest, callOptions ...callopt.Option) (r *user.UserLogOutResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) UserSignUp(ctx context.Context, Req *user.UserSignUpRequest, callOptions ...callopt.Option) (r *user.UserSignUpResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserSignUp(ctx, Req)
}

func (p *kUserServiceClient) UserLogIn(ctx context.Context, Req *user.UserLogInRequest, callOptions ...callopt.Option) (r *user.UserLogInResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogIn(ctx, Req)
}

func (p *kUserServiceClient) UserLogOut(ctx context.Context, Req *user.UserLogOutRequest, callOptions ...callopt.Option) (r *user.UserLogOutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogOut(ctx, Req)
}
